#!/bin/bash
set -e
trap "jobs -p | xargs -r kill" EXIT

if [ Tracker.class -ot Tracker.java ] || [ Transport.class -ot Tracker.java ]; then
    javac -sourcepath . Tracker.java
fi
if [ Game.class -ot Game.java ] || [ Transport.class -ot Game.java ] || [ Tracker.class -ot Game.java ]; then
    javac -sourcepath . Game.java
fi

java -ea Tracker 6789 15 10 &
java StressTest 127.0.0.1 6789 "java -ea Game"
